name: Woodstock City Builders
favicon: null
layout_spectrum: 0.9626542739570141
typography_spectrum: 0.5958255601581186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7821996472775936
  lightness: 0.23446353618055582
  saturation: 0.34659767779521644
  rhythmicContrast: 0.2703599294181913
purpose: []
